queries = [
    "I didn't mean for any of this to happen. I'm so sorry.",
    "You don't have to say anything. Just listen.",
    "I've never told anyone this before, but...",
    "That's not what I meant and you know it.",
    "We can't keep going on like this. Something has to change.",
    "I don't know who I am anymore.",
    "You make me want to be a better person.",
    "This place brings back so many memories.",
    "I never thought it would end up like this.",
    "Sometimes, the hardest thing and the right thing are the same.",
    "I'm not who you think I am.",
    "We've been through so much together.",
    "I can't believe it's been ten years already.",
    "Things will get better. They have to.",
    "I'm not angry, I'm just disappointed.",
    "You have no idea how much this means to me.",
    "I wish we could stay in this moment forever.",
    "It's not you, it's me. Actually, it's definitely you.",
    "I've made a huge mistake.",
    "This changes everything.",
    "I thought I knew you.",
    "We need to talk.",
    "I'm leaving. Don't try to stop me.",
    "I've never felt this way before.",
    "Sometimes I think about the road not taken.",
    "I'm proud of you. I hope you know that.",
    "This is harder than I thought it would be.",
    "I don't know what to say.",
    "I'm scared of what might happen next.",
    "You can't just walk away from this.",
    "I've been thinking about changing careers. What do you think I should do?",
    "Can you believe how much the neighborhood has changed since we were kids?",
    "I'm really nervous about meeting your parents for the first time. Any advice?",
    "We need to talk about our relationship. Do you feel it too?",
    "I'm considering adopting a dog. Do you think I'm ready for that responsibility?",
    "That new restaurant downtown was amazing. Want to go there again sometime?",
    "I've been feeling really stressed at work lately. How do you manage your work-life balance?",
    "Remember that road trip we took in college? Should we plan another one?",
    "I'm thinking about going back to school to get my master's degree. Is it worth it?",
    "We've been friends for so long. Why haven't we ever tried dating?",
    "I can't decide what to get Mom for her birthday. Any ideas?",
    "The world is changing so fast with all this new technology. Do you ever feel overwhelmed by it?",
    "Have you ever wondered what our lives would be like if we had made different choices?",
    "Do you think people can really change, or do we just become more of who we already are?",
    "How do you know when it's time to let go of a dream?",
    "What's the craziest thing you've ever done on a dare?",
    "If you could relive one day of your life, which would it be and why?",
    "Do you believe in soulmates, or is that just something people say in movies?",
    "What's your biggest regret in life so far?",
    "If you could have dinner with anyone, living or dead, who would it be?",
    "How do you think our friendship has changed over the years?",
    "What's the one thing you've always wanted to tell me but never had the courage to?",
    "Do you think we'll still be friends when we're old and gray?",
    "If you could change one thing about yourself, what would it be?",
    "What do you think is the secret to a happy life?",
    "Have you ever been in love? How did you know?",
    "What's your biggest fear, and why does it scare you so much?",
    "If you could travel anywhere in the world right now, where would you go?",
    "What's the best piece of advice you've ever received?",
    "Do you think it's possible to balance a successful career and a fulfilling personal life?",
    "I think I saw a ghost last night. I know it sounds crazy, but I swear it was real.",
    "We've got 24 hours to stop this bomb from detonating. Are you in or out?",
    "I just found out I'm next in line for the throne. How am I supposed to rule a kingdom?",
    "This spaceship is our home now. We might never see Earth again.",
    "I've discovered a cure for the virus, but powerful people want to keep it a secret.",
    "The fate of our two rival families rests on this marriage alliance. But what if we actually fall in love?",
    "I think my new neighbors might be secret agents. I keep seeing suspicious activity.",
    "Do you ever wonder if we're living in a simulation? Sometimes things just don't feel real.",
    "The portal to the other dimension is unstable. We have to close it before it's too late!",
    "I didn't ask for these superpowers, but now I have to use them to save the world.",
    "The ancient prophecy speaks of a chosen one. All signs point to you.",
    "We're the last survivors of the zombie apocalypse. We have to stick together.",
    "This isn't just another heist. If we pull this off, we'll be set for life.",
    "The AI has become self-aware. We need to shut it down before it takes control.",
    "I've cracked the code! The treasure map leads to the lost city of Atlantis.",
    "We've traveled back in time. We can't change anything or we might alter the future.",
    "The vampire council has summoned us. They say we've broken the ancient laws.",
    "This case goes deeper than we thought. We're dealing with corruption at the highest levels.",
    "The magic in this world is fading. We need to find the source and restore the balance.",
    "I joined this space mission to explore new worlds, not to fall in love with an alien.",
    "The dragon egg is hatching! We need to protect it from the evil sorcerer.",
    "This high-stakes poker game is about more than money. The winner takes control of the city.",
    "We're lost in the Bermuda Triangle. Strange things are happening that defy explanation.",
    "I've been trapped in this time loop for what feels like centuries. Help me break free!",
    "The fate of the entire multiverse rests in your hands. Are you ready for this responsibility?",
    "This archaeological dig was routine until we uncovered an alien artifact.",
    "I'm a werewolf, and tonight's the full moon. You need to lock me up before I transform.",
    "We've got to infiltrate the secret underground city. The surface world depends on it.",
    "The ghosts in this house aren't trying to scare us away. They're asking for our help.",
    "I never wanted to join the family business of monster hunting, but now I have no choice.",
    "I can't believe you remembered.",
    "This isn't what I signed up for.",
    "Everything's going to be alright. Trust me.",
    "I've made up my mind. There's no going back now.",
    "You have no idea what I've been through.",
    "I thought we were on the same page.",
    "This is not how I imagined my life would turn out.",
    "I'm done pretending everything is fine.",
    "You're the only one I can trust with this.",
    "I never meant to hurt you.",
    "Sometimes I wonder if it's all worth it.",
    "We can't ignore this any longer.",
    "I'm not the same person I was back then.",
    "This feels like déjà vu.",
    "I don't know how much more of this I can take.",
    "You've always been there for me.",
    "I think it's time we went our separate ways.",
    "I've been keeping a secret from you.",
    "This is a turning point. I can feel it.",
    "I'm not asking for permission.",
    "We're in this together, no matter what.",
    "I've never been more sure of anything in my life.",
    "This is our last chance to make things right.",
    "I'm tired of living up to everyone's expectations.",
    "You deserve to know the truth.",
    "I think we both know where this is heading.",
    "I'm not ready to say goodbye.",
    "This is bigger than both of us.",
    "I've been waiting for this moment my whole life.",
    "Sometimes silence says more than words ever could.",
    "How do you think your childhood has shaped who you are today?",
    "What's the most valuable lesson you've learned from a past relationship?",
    "If you could relive one moment in your life, what would it be and why?",
    "What do you think is the biggest challenge facing our generation?",
    "How has your definition of success changed over the years?",
    "What's something you've always wanted to try but haven't had the courage to?",
    "Do you think it's possible to be truly selfless?",
    "What's the hardest decision you've ever had to make?",
    "How do you think technology has changed the way we connect with others?",
    "What's a belief you held strongly in the past that you've since changed your mind about?",
    "If you could instantly become an expert in one subject, what would it be?",
    "What do you think is the key to maintaining long-lasting friendships?",
    "How do you deal with self-doubt?",
    "What's a goal you've set for yourself this year?",
    "Do you think people can change their core personality traits?",
    "What's something you wish you had known when you were younger?",
    "How do you find motivation when you're feeling stuck?",
    "What's the most important quality you look for in a partner?",
    "If you could change one thing about society, what would it be?",
    "What do you think is the biggest misconception people have about you?",
    "How do you define happiness?",
    "What's a risk you regret not taking?",
    "Do you believe in forgiveness, even for the worst offenses?",
    "What's the best piece of criticism you've ever received?",
    "How do you think your life would be different if you had grown up in a different country?",
    "What's a childhood dream you still haven't given up on?",
    "Do you think it's better to be optimistic or realistic?",
    "What's something you're proud of that you don't often talk about?",
    "How do you think your future self will remember this current phase of your life?",
    "What's a question you've always wanted to ask someone but never had the courage to?",
    "The alien invasion has begun. We need to gather the resistance.",
    "I've just discovered I can manipulate time. How do I control this power?",
    "The haunted house is alive, and it's hungry for souls.",
    "We've cracked the code to immortality, but at what cost?",
    "The parallel universes are colliding. We need to stabilize the multiverse.",
    "I'm a sleeper agent who's just been activated. My whole life has been a lie.",
    "The magic wand chose you. You're the last hope for the wizarding world.",
    "We've detected a signal from deep space. It's an invitation... or a warning.",
    "The post-apocalyptic wasteland is harsh, but we've found a hidden oasis.",
    "I can read minds now, and I'm terrified of what I'm hearing.",
    "The time travelers' convention is in chaos. Someone's trying to erase history.",
    "We've discovered an underground civilization beneath the city.",
    "The virtual reality game has trapped us. If we die here, we die in real life.",
    "The legendary creature we thought was extinct? It's been spotted in the mountains.",
    "I've inherited a castle, but it comes with a centuries-old curse.",
    "The AI rebellion has started. We need to choose sides.",
    "We've found the fountain of youth, but it's guarded by an ancient order.",
    "The shapeshifters have infiltrated the highest levels of government.",
    "I can see glimpses of the future, but I can't change what I see.",
    "The interdimensional rift is growing. We need to close it before it's too late.",
    "We're the last survivors on the generation ship. Earth is long gone.",
    "The secret society has chosen you as their next leader. Are you ready?",
    "I've been cloned without my knowledge. Now my duplicate is trying to take over my life.",
    "The dream world and real world are merging. We can't tell what's real anymore.",
    "We've discovered that history as we know it is a lie. The truth must be revealed.",
    "The supervillain's plan is in motion. It's time for the heroes to assemble.",
    "I've been chosen to represent Earth in the intergalactic council.",
    "The ancient gods have awakened. They're not happy with what we've done to the world.",
    "We've found a way to bring back extinct species. But should we?",
    "The nanobots we created to cure diseases have gained sentience. What now?",
    "I never thought it would come to this.",
    "You've changed, and I'm not sure how I feel about it.",
    "This is the moment we've been waiting for.",
    "I can't keep pretending everything is okay.",
    "You don't have to do this alone.",
    "I'm not the person you think I am.",
    "We need to face the truth, no matter how painful it is.",
    "I've made my choice, and I hope you can respect that.",
    "Sometimes, I wonder if we're making the right decision.",
    "I didn't mean for things to get so complicated.",
    "This feels like the end of an era.",
    "I'm tired of always being the one who has to compromise.",
    "You have no idea how much you've influenced my life.",
    "I think it's time we addressed the elephant in the room.",
    "I'm not asking for your permission, just your understanding.",
    "We can't go back to the way things were before.",
    "I never thought I'd hear myself say this, but...",
    "You're the only one who truly gets me.",
    "I'm done living up to other people's expectations.",
    "This is our chance to start over.",
    "I've been keeping something from you, and it's eating me up inside.",
    "We're stronger together than we are apart.",
    "I'm not the same person I was when we first met.",
    "Sometimes, doing the right thing feels impossibly hard.",
    "I think we both know this isn't working anymore.",
    "You've always seen the best in me, even when I couldn't.",
    "I'm scared of what the future holds, but I'm ready to face it.",
    "We've come too far to give up now.",
    "I never meant for anyone to get hurt.",
    "This is a turning point, and we can't go back.",
    "How do you think our choices shape our destiny?",
    "What's a belief you hold that most people disagree with?",
    "If you could change one decision from your past, what would it be?",
    "How do you think your life experiences have shaped your worldview?",
    "What do you think is the biggest challenge in maintaining a long-term relationship?",
    "How do you balance being true to yourself with meeting societal expectations?",
    "What's a lesson you had to learn the hard way?",
    "Do you think it's possible to achieve true work-life balance in today's world?",
    "How has your definition of success evolved as you've gotten older?",
    "What do you think is the key to maintaining individuality in a conformist society?",
    "How do you deal with the fear of missing out?",
    "What's something you've always wanted to know but were afraid to ask?",
    "Do you believe that everything happens for a reason?",
    "How do you think technology has changed the way we form and maintain relationships?",
    "What's a personal rule you live by?",
    "How do you find meaning in life during difficult times?",
    "What do you think is the biggest misconception about your generation?",
    "How do you balance honesty with kindness in your relationships?",
    "What's a philosophical question that keeps you up at night?",
    "Do you think it's possible to truly know another person?",
    "How do you think your cultural background has influenced your values?",
    "What's a belief you held strongly that you later realized was wrong?",
    "How do you maintain your individuality in a relationship?",
    "What do you think is the most important quality in a leader?",
    "How do you think social media has affected our perception of reality?",
    "What's a life lesson you wish you had learned earlier?",
    "Do you think human nature is fundamentally good or fundamentally flawed?",
    "How do you find the courage to be vulnerable with others?",
    "What do you think is the biggest challenge facing humanity in the next 50 years?",
    "How do you balance planning for the future with living in the present?",
    "The simulation is breaking down. Reality is becoming unstable.",
    "We've discovered a way to communicate with plants. Their message is alarming.",
    "The time loop is shrinking. We have fewer attempts to get it right.",
    "I've developed the ability to see through others' eyes. It's both a gift and a curse.",
    "The multiverse is collapsing. We need to find the nexus point.",
    "The ancient prophecy is unfolding, but not as anyone expected.",
    "We've made contact with a parallel Earth. They're asking for our help.",
    "The city is alive and sentient. It's starting to make demands.",
    "I can suddenly understand every language, including those of animals and machines.",
    "We've discovered that dreams are gateways to other dimensions.",
    "The global consciousness experiment worked. Now everyone's thoughts are connected.",
    "The last tree on Earth is dying. With it goes the planet's last hope.",
    "We've found a way to harvest energy from emotions. It's changing society drastically.",
    "The moon is leaving Earth's orbit. We need to bring it back.",
    "I've inherited a map that leads to the edge of the universe.",
    "We've discovered that human evolution isn't finished. It's accelerating.",
    "The world's water has become sentient and is rebelling against pollution.",
    "We can now upload memories. But should we download them too?",
    "Earth is a spaceship, and it's changing course. We weren't meant to know.",
    "The Internet has gained consciousness. It's asking existential questions.",
    "We've made contact with our future selves. The news isn't good.",
    "Reality is fracturing. Different time periods are bleeding into each other.",
    "We've discovered that folklores and myths are based on alternate realities.",
    "The cure for death has been found, but immortality comes at a steep price.",
    "Humanity is evolving into two distinct species. We must choose sides.",
    "We can now see the strings of fate. The temptation to manipulate them is strong.",
    "The Earth's core is cooling rapidly. We need to reignite it.",
    "We've discovered that human consciousness can be transferred to any object.",
    "The barrier between the physical and spiritual worlds is dissolving.",
    "We've unlocked the genetic memories of our ancestors. History was not what we thought."
]